# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'PicturePerfect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  
  # Pods for PicturePerfect
  pod 'GoogleMLKit/FaceDetection'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
  

end
